[package]
name = "async_await"
version = "0.1.0"
edition = "2021"

[dependencies]
trpl = { version = "0.1.0", path = "../../../packages/trpl" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
